### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
  description: O Microsoft Application Virtualization Hosting 5.1 para Áreas de Trabalho do Windows segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
summary: |+
  O Microsoft Application Virtualization Hosting 5.1 para Áreas de Trabalho do Windows segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).

  Isso se aplica às seguintes edições: para Áreas de Trabalho do Windows

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Links 
  * [Informações sobre o produto](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Edições 
  * para Áreas de Trabalho do Windows