### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: O Microsoft System Center Configuration Manager 2007 R2 segue a Política de Ciclo de Vida Fixa.
  ms.date: 07/28/2020
  ms.openlocfilehash: d74ead7a94de9a66a4f34abab6d8ff9b4496c86479bf1242d36b903855a6e66f
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511265"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  O Microsoft System Center Configuration Manager 2007 R2 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > O suporte para esse produto foi encerrado. Veja as diretrizes de migração abaixo.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Links \n* [Diretrizes de migração](/mem/configmgr/core/migration/planning-for-migration)\n* [Diretrizes de migração adicionais](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
