### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: O Microsoft Forefront Client Security segue a política de ciclo de vida fixo.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924243"
name: Microsoft Forefront Client Security
summary: >+
  O Microsoft Forefront Client Security segue a política de ciclo de vida [fixo](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Links \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> O Forefront Client Security foi descontinuado a partir de 14 de julho de 2015. As atualizações de definições antimalware e anti-spyware não estarão mais disponíveis após o fim do suporte para a versão do produto. Avalie o System Center Endpoint Protection como uma substituição."
