### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4,6
  description: O Microsoft Application Virtualization 4,6 segue a política de ciclo de vida fixo.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "803814"
name: Microsoft Application Virtualization 4,6
summary: >+
  O Microsoft Application Virtualization 4,6 segue a política de ciclo de vida [fixo](/lifecycle/policies/fixed) .


  Isso se aplica às seguintes edições: para serviços de área de trabalho remota, para áreas de trabalho do Windows, sequenciador

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Links \n* [Informações sobre produtos e migração](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Diretrizes de migração](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Política de Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Como o cliente 4,6 do App-V utiliza o servidor App-V 4,5, o servidor do App-V 4,5 continuará a ter suporte de acordo com as datas de ciclo de vida do App-V 4,6 quando estiver em uso com o cliente App-V 4,6 com suporte.\n\n## <a name=\"editions\"></a>Das \n* para serviços de área de trabalho remota\n* para áreas de trabalho do Windows\n* Sequencer"
