### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: O Microsoft System Center Configuration Manager 2007 R3 segue a Política de Ciclo de Vida Fixa.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  O Microsoft System Center Configuration Manager 2007 R3 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  > [!IMPORTANT]
  > O suporte para esse produto foi encerrado. Veja as diretrizes de migração abaixo.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Links 
  * [Diretrizes de migração](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Diretrizes de migração adicionais](/mem/configmgr/core/migration/planning-for-migration)