### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization hospedando 5,1 para áreas de trabalho do Windows
  description: O Microsoft Application Virtualization Hosting 5,1 for Windows desktops segue a política de ciclo de vida fixo.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "848424"
name: Microsoft Application Virtualization hospedando 5,1 para áreas de trabalho do Windows
summary: >+
  O Microsoft Application Virtualization Hosting 5,1 for Windows desktops segue a política de ciclo de vida [fixo](/lifecycle/policies/fixed) .


  Isso se aplica às seguintes edições: para áreas de trabalho do Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Links \n* [Informações do produto](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Das \n* para áreas de trabalho do Windows"
