### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: O Microsoft Application Virtualization 5.1 segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/10/2020
  keywords: for Remote Desktop Services,for Windows Desktops
  ms.openlocfilehash: b6ca3da5136031bbb6e140f3fa5124ef7b2e4ed6
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1001932"
name: Microsoft Application Virtualization 5.1
summary: >+
  O Microsoft Application Virtualization 5.1 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  Isso se aplica às seguintes edições: para Serviços de Área de Trabalho Remota, para Áreas de Trabalho do Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Links \n* [Informações sobre o produto](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Edições \n* para Serviços de Área de Trabalho Remota\n* para Áreas de Trabalho do Windows"
