### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5,1
  description: O Microsoft Application Virtualization 5,1 segue a política de ciclo de vida fixo.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "848242"
name: Microsoft Application Virtualization 5,1
summary: >+
  O Microsoft Application Virtualization 5,1 segue a política de ciclo de vida [fixo](/lifecycle/policies/fixed) .


  Isso se aplica às seguintes edições: para serviços de área de trabalho remota, para áreas de trabalho do Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Links \n* [Informações do produto](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Das \n* para serviços de área de trabalho remota\n* para áreas de trabalho do Windows"
