### YamlMime:Lifecycle
metadata:
  title: Gateway de aplicativo inteligente de comunicações de baixo
  description: Comunicações de baixo o gateway de aplicativo inteligente segue a política de ciclo de vida fixo.
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907128"
name: Gateway de aplicativo inteligente de comunicações de baixo
summary: >+
  Comunicações de baixo o gateway de aplicativo inteligente segue a política de ciclo de vida [fixo](/lifecycle/policies/fixed) .


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> O suporte para este produto está sujeito aos termos de sua aquisição."
